### PR TITLE
Add config as a command-line argument.

### PR DESCRIPTION
**Pull request by b10n**
I added this to be able to control multiple PowerMates. Now I can launch one instance with a different configuration for each PowerMate. It's not the most elegant solution, but it works.

### CODE REVIEW

**Comment by stefansundin** [comment]
Wow, you have multiple powermates? :) Feel free to share more about how you use them.

I only have one and I had to have it shipped from abroad because I couldn't find any local retailer.. I wonder if the new bluetooth one is any good..

I think we should merge this, but I will make some minor changes first. I'll let you comment on my changes before I merge.

**Comment by stefansundin** [comment]
Okay, I think that's it, let me know what you think.

I'm ok with looping over argv multiple times if it makes the code a little bit simpler. I think it does in this case.

**Comment by b10n** [comment]
I have two PowerMates lying around. The second one I received more or less by accident :)
Something I've been thinking about is integrating it with OpenHAB or HomeAssistant to control the brightness and color of my smart lights.

Anyway, thanks for the quick review. One thing I noticed is that now it doesn't complain if wrong arguments are supplied or if the filename is missing. Was it your intention to skip this check?

**Comment by stefansundin** [comment]
I did realize that that was something I removed.. at first I was just going to reply with "I'm fine with skipping that if it makes the code cleaner", but then I realized that I could add it back without moving all the argument parsing back to a single place.

It took me a while to get the if statement working, but I think it's pretty clean now that I got it working and put some comments there. It was far more confusing when I was in the middle of writing it.

Actually, I guess I don't need the explicit check for `-h` or `--help` since that would trigger if it's an unknown option. The way you had it at first.

**Comment by b10n** [comment]
Okay, I simplified the code a tiny bit more. I also think that the argument parsing is pretty neat now.

**Comment by stefansundin** [comment]
Nice. I'll release this now.

**Pull request merged**
